### ISSUE TITLE
【Bug】dotnet 安装网络异常

### ISSUE THREAD

**Issue by nibazshab** [RayWangQvQ/BiliBiliToolPro#316]
qinglong 运行，在安装 dotnet 这一步骤卡住了

dotnet 安装脚本运行到一半就没有反应了，等了半个多小时都是这样

```
--2022-11-15 13:05:56--  https://ghproxy.com/https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/qinglong/ray-dotnet-install.sh
Resolving ghproxy.com (ghproxy.com)... 140.83.35.89
Connecting to ghproxy.com (ghproxy.com)|140.83.35.89|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 386 [text/plain]
Saving to: 'STDOUT'

-                         100%[==================================>]     386  --.-KB/s    in 0s

2022-11-15 13:05:57 (285 MB/s) - written to stdout [386/386]


-------set up dot net env-------
OK: 133 MiB in 80 packages
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars
dotnet-install: Calling: get_normalized_architecture_from_architecture <auto>
dotnet-install: Calling: get_machine_architecture
dotnet-install: Normalized architecture: 'x64'.
dotnet-install: Calling: get_normalized_os
dotnet-install: Calling: get_current_os_name
dotnet-install: Calling: get_linux_platform_name
dotnet-install: Normalized OS: 'linux-musl'.
dotnet-install: Calling: get_normalized_quality
dotnet-install: Normalized quality: ''.
dotnet-install: Calling: get_normalized_channel 6.0
dotnet-install: Normalized channel: '6.0'.
dotnet-install: Calling: get_normalized_product
dotnet-install: Normalized product: 'dotnet-sdk'.
dotnet-install: Calling: resolve_installation_path <auto>
dotnet-install: Calling: get_user_install_path
dotnet-install: resolve_installation_path: user_install_path=/root/.dotnet
dotnet-install: InstallRoot: '/root/.dotnet'.
dotnet-install: Calling: get_normalized_architecture_for_specific_sdk_version Latest 6.0 x64
dotnet-install: Calling: get_current_os_name
dotnet-install: Calling: get_linux_platform_name
dotnet-install: Calling: get_download_link_from_aka_ms
dotnet-install: Retrieving primary payload URL from aka.ms for channel: '6.0', quality: '', product: 'dotnet-sdk', os: 'linux-musl', architecture: 'x64'.
dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz'.
dotnet-install: Calling: get_http_header https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz true
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: get_http_header_curl https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz true
dotnet-install: Received response: HTTP/1.1 301 Moved Permanently
Server: Kestrel
Location: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
Request-Context: appId=cid-v1:9b037ab9-fa5a-4c09-81bd-41ffa859f01e
X-Response-Cache-Status: True
Content-Length: 0
Expires: Tue, 15 Nov 2022 05:05:59 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 15 Nov 2022 05:05:59 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

HTTP/2 200
accept-ranges: bytes
age: 548453
content-md5: rJa/QYSioJN/DgHQUjIRXg==
content-type: application/octet-stream
date: Tue, 15 Nov 2022 05:06:01 GMT
etag: 0x8DAC0F9BB0D8675
last-modified: Mon, 07 Nov 2022 19:53:24 GMT
server: ECAcc (hkc/BD12)
x-cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: 12deb4c8-301e-0041-7db2-f3107a000000
x-ms-version: 2009-09-19
content-length: 184956624

dotnet-install: The redirect location retrieved: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz'.
dotnet-install: Retrieved primary payload URL from aka.ms link: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz'.
dotnet-install: Downloading using legacy url will not be attempted.
dotnet-install: Version: '6.0.403'.
dotnet-install: Calling: get_specific_product_version  6.0.403 https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Calling: get_specific_product_version_url  6.0.403 true https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url  6.0.403 false https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: is_dotnet_package_installed /root/.dotnet sdk 6.0.403
dotnet-install: Calling: combine_paths /root/.dotnet sdk
dotnet-install: combine_paths: root_path=/root/.dotnet
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /root/.dotnet/sdk 6.0.403
dotnet-install: combine_paths: root_path=/root/.dotnet/sdk
dotnet-install: combine_paths: child_path=6.0.403
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/root/.dotnet/sdk/6.0.403
dotnet-install: Generated 1 links.
dotnet-install: Link 0: aka.ms, 6.0.403, https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Calling: install_dotnet
dotnet-install: Zip path: /tmp/dotnet.9CLIvXWpz
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Calling: download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz /tmp/dotnet.9CLIvXWpz
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: downloadcurl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz /tmp/dotnet.9CLIvXWpz


```

等待近一个小时后，给出的如下信息

```
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
dotnet-install: Calling: get_http_header_curl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz false
dotnet-install: Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz.
dotnet-install: Download failed: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Failed to download aka.ms link 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz': Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz.
dotnet-install: Temporary zip file /tmp/dotnet.9CLIvXWpz was removed
dotnet_install: Error: Could not find `.NET Core SDK` with version = 6.0.403
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
sh: dotnet: not found

-------set up dot net env finish-------
```

**Comment by cnxjg** [comment]
应该是网络问题

**Comment by RayWangQvQ** [comment]
网络问题，没下载下来。
你是不是墙外的网络环境？
微软官方的dotnet安装脚本很神奇，墙内需要`--no-cdn`，墙外不需要。

墙外可以试试`curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --verbose`

**Comment by cnxjg** [comment]
> 官方

我没有开启科学上网下载不下来，开启了才可以下载

**Comment by nibazshab** [comment]
不是，我是国内上海的服务器，用这个脚本有一个多月了dotnet一直都好得很，前天突然出现的这个毛病

**Comment by cnxjg** [comment]
我是自己家里的宽带，更新之前可以，更新后就一直安装不上，和他的提示一样，但是开了科学又能安装上。

**Comment by nibazshab** [comment]
看这个提示信息，会不会是因为青龙更新后没有自带 openssl 然后无法连接 https 导致的？

```
root@056a940c668b:/ql $ curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --no-cdn
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
dotnet-install: Download attempt #1 has failed: 200 Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz.
dotnet-install: Attempt #2 will start in 10 seconds.
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
dotnet-install: Download attempt #2 has failed: 200 Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz.
dotnet-install: Attempt #3 will start in 20 seconds.
```

**Comment by RayWangQvQ** [comment]
网络异常的有多少人，可以冒个泡。如果很普遍，我可以把安装脚本从官方版再改回去

**Comment by yidongxu125** [comment]
异常，去掉cdn还是不行

**Comment by yidongxu125** [comment]
> 网络异常的有多少人，可以冒个泡。如果很普遍，我可以把安装脚本从官方版再改回去

去掉和不去cdn都不行，都无法下载

**Comment by yidongxu125** [comment]
> 网络异常的有多少人，可以冒个泡。如果很普遍，我可以把安装脚本从官方版再改回去

最早的6.0.101下载很快，这个6.0.403下不动

**Comment by yidongxu125** [comment]
-------set up dot net env-------
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars 
dotnet-install: Calling: get_normalized_architecture_from_architecture <auto>
dotnet-install: Calling: get_machine_architecture 
dotnet-install: Normalized architecture: 'x64'.
dotnet-install: Calling: get_normalized_os 
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_linux_platform_name 
dotnet-install: Normalized OS: 'linux-musl'.
dotnet-install: Calling: get_normalized_quality 
dotnet-install: Normalized quality: ''.
dotnet-install: Calling: get_normalized_channel 6.0
dotnet-install: Normalized channel: '6.0'.
dotnet-install: Calling: get_normalized_product 
dotnet-install: Normalized product: 'dotnet-sdk'.
dotnet-install: Calling: resolve_installation_path <auto>
dotnet-install: Calling: get_user_install_path 
dotnet-install: resolve_installation_path: user_install_path=/root/.dotnet
dotnet-install: InstallRoot: '/root/.dotnet'.
dotnet-install: Calling: get_normalized_architecture_for_specific_sdk_version Latest 6.0 x64
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_linux_platform_name 
dotnet-install: Calling: get_download_link_from_aka_ms 
dotnet-install: Retrieving primary payload URL from aka.ms for channel: '6.0', quality: '', product: 'dotnet-sdk', os: 'linux-musl', architecture: 'x64'.
dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz'.
dotnet-install: Calling: get_http_header https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz true
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: get_http_header_curl https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz true
dotnet-install: Received response: HTTP/1.1 301 Moved Permanently
Server: Kestrel
Location: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
Request-Context: appId=cid-v1:7d63747b-487e-492a-872d-762362f77974
X-Response-Cache-Status: True
Content-Length: 0
Expires: Wed, 16 Nov 2022 14:20:28 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 16 Nov 2022 14:20:28 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

HTTP/2 200 
accept-ranges: bytes
age: 63323
content-md5: rJa/QYSioJN/DgHQUjIRXg==
content-type: application/octet-stream
date: Wed, 16 Nov 2022 14:20:34 GMT
etag: 0x8DAC0F9BB0D8675
last-modified: Mon, 07 Nov 2022 19:53:24 GMT
server: ECAcc (hkc/BD12)
x-cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: 2ea5ab0e-301e-010a-1433-f967b5000000
x-ms-version: 2009-09-19
content-length: 184956624

dotnet-install: The redirect location retrieved: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz'.
dotnet-install: Retrieved primary payload URL from aka.ms link: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz'.
dotnet-install: Downloading using legacy url will not be attempted.
dotnet-install: Version: '6.0.403'.
dotnet-install: Calling: get_specific_product_version  6.0.403 https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Calling: get_specific_product_version_url  6.0.403 true https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url  6.0.403 false https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: is_dotnet_package_installed /root/.dotnet sdk 6.0.403
dotnet-install: Calling: combine_paths /root/.dotnet sdk
dotnet-install: combine_paths: root_path=/root/.dotnet
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /root/.dotnet/sdk 6.0.403
dotnet-install: combine_paths: root_path=/root/.dotnet/sdk
dotnet-install: combine_paths: child_path=6.0.403
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/root/.dotnet/sdk/6.0.403
dotnet-install: Generated 1 links.
dotnet-install: Link 0: aka.ms, 6.0.403, https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Calling: install_dotnet 
dotnet-install: Zip path: /tmp/dotnet.7J2jJUr4j
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
dotnet-install: Calling: download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz /tmp/dotnet.7J2jJUr4j
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: downloadcurl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz /tmp/dotnet.7J2jJUr4j

**Comment by RayWangQvQ** [comment]
extra.sh里的安装语句，改成`curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/qinglong/ray-dotnet-install.sh | bash /dev/stdin --no-official`试试看

**Comment by yidongxu125** [comment]
> curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/qinglong/ray-dotnet-install.sh | bash /dev/stdin --no-official



-------set up dot net env-------
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
--2022-11-16 22:57:04--  https://download.visualstudio.microsoft.com/download/pr/b5e6c72e-457c-406c-a4a8-6a4fcdd5f50c/feaa81a666c8942064453fb3c456856b/dotnet-sdk-6.0.403-linux-musl-x64.tar.gz
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 117.24.10.17
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|117.24.10.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 184956624 (176M) [application/octet-stream]
Saving to: 'dotnet-sdk.tar.gz'

     0K .......... .......... .......... .......... ..........  0% 1017K 2m58s
    50K .......... .......... .......... .......... ..........  0% 1.28M 2m38s
   100K .......... .......... .......... .......... ..........  0% 10.5M 1m51s


搞定，大神就是不一样

**Comment by RayWangQvQ** [comment]
文档已添加说明： https://github.com/RayWangQvQ/BiliBiliToolPro/tree/main/qinglong#11-%E5%AE%89%E8%A3%85-dotnet-%E7%8E%AF%E5%A2%83

优先考虑使用官方脚本安装，如果实在不行，再`--no-official`

**Comment by nibazshab** [comment]
好的这下ok了，谢过大佬了

**Comment by a1092595196** [comment]
otnet-install: combine_paths: child_path=6.0.403
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/root/.dotnet/sdk/6.0.403
dotnet-install: .NET Core SDK with version '6.0.403' is already installed.
创建软链接...
/dev/stdin: line 108: /usr/local/bin/dotnet: No such file or directory

-------set up dot net env finish-------
