### ISSUE TITLE
安装 dotnet 环境时报错

### ISSUE THREAD

**Issue by Testplayers** [RayWangQvQ/BiliBiliToolPro#328]
[root@h1n1exssi4x6odrx ~]# docker exec -it qinglong bash /ql/config/extra.sh
--2022-11-22 22:54:19--  https://ghproxy.com/https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/qinglong/ray-dotnet-install.sh
Resolving ghproxy.com (ghproxy.com)... 129.151.136.35
Connecting to ghproxy.com (ghproxy.com)|129.151.136.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3178 (3.1K) [text/plain]
Saving to: 'STDOUT'

-                               100%[=======================================================>]   3.10K  --.-KB/s    in 0s      

2022-11-22 22:54:20 (268 MB/s) - written to stdout [3178/3178]

-------set up dot net env-------
sh: syntax error: unexpected "("

**Comment by RayWangQvQ** [comment]
`docker exec -it qinglong bash catch /ql/config/extra.sh`

**Comment by a1092595196** [comment]
qinglong:2.15.1
arm64
-------set up dot net env-------
安装依赖...
OK: 107 MiB in 79 packages
install by offical script...
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars 
dotnet-install: Calling: get_normalized_architecture_from_architecture <auto>
dotnet-install: Calling: get_machine_architecture 
dotnet-install: Normalized architecture: 'arm64'.
dotnet-install: Calling: get_normalized_os 
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_linux_platform_name 
dotnet-install: Normalized OS: 'linux-musl'.
dotnet-install: Calling: get_normalized_quality 
dotnet-install: Normalized quality: ''.
dotnet-install: Calling: get_normalized_channel 6.0
dotnet-install: Normalized channel: '6.0'.
dotnet-install: Calling: get_normalized_product 
dotnet-install: Normalized product: 'dotnet-sdk'.
dotnet-install: Calling: resolve_installation_path <auto>
dotnet-install: Calling: get_user_install_path 
dotnet-install: resolve_installation_path: user_install_path=/root/.dotnet
dotnet-install: InstallRoot: '/root/.dotnet'.
dotnet-install: Calling: get_normalized_architecture_for_specific_sdk_version Latest 6.0 arm64
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_linux_platform_name 
dotnet-install: Calling: get_download_link_from_aka_ms 
dotnet-install: Retrieving primary payload URL from aka.ms for channel: '6.0', quality: '', product: 'dotnet-sdk', os: 'linux-musl', architecture: 'arm64'.
dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz'.
dotnet-install: Calling: get_http_header https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz true
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: get_http_header_curl https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz true
dotnet-install: Received response: HTTP/1.1 301 Moved Permanently
Server: Kestrel
Location: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz
Request-Context: appId=cid-v1:7d63747b-487e-492a-872d-762362f77974
X-Response-Cache-Status: True
Content-Length: 0
Expires: Sun, 27 Nov 2022 13:55:07 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sun, 27 Nov 2022 13:55:07 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

HTTP/2 200 
accept-ranges: bytes
age: 364968
content-md5: SvTRpTqhouBq/1CwqRml+Q==
content-type: application/octet-stream
date: Sun, 27 Nov 2022 13:55:09 GMT
etag: 0x8DAC0F9AC286E08
last-modified: Mon, 07 Nov 2022 19:52:59 GMT
server: ECAcc (saa/8307)
x-cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: 0f5a2aa1-801e-00f9-1416-fff289000000
x-ms-version: 2009-09-19
content-length: 179310623

dotnet-install: The redirect location retrieved: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz'.
dotnet-install: Retrieved primary payload URL from aka.ms link: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz'.
dotnet-install: Downloading using legacy url will not be attempted.
dotnet-install: Version: '6.0.403'.
dotnet-install: Calling: get_specific_product_version  6.0.403 https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz
dotnet-install: Calling: get_specific_product_version_url  6.0.403 true https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url  6.0.403 false https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: is_dotnet_package_installed /root/.dotnet sdk 6.0.403
dotnet-install: Calling: combine_paths /root/.dotnet sdk
dotnet-install: combine_paths: root_path=/root/.dotnet
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /root/.dotnet/sdk 6.0.403
dotnet-install: combine_paths: root_path=/root/.dotnet/sdk
dotnet-install: combine_paths: child_path=6.0.403
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/root/.dotnet/sdk/6.0.403
dotnet-install: .NET Core SDK with version '6.0.403' is already installed.
创建软链接...
/dev/stdin: line 108: /usr/local/bin/dotnet: No such file or directory

-------set up dot net env finish-------

**Comment by RayWangQvQ** [comment]
> qinglong:2.15.1 arm64 -------set up dot net env------- 安装依赖... OK: 107 MiB in 79 packages install by offical script... dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where: dotnet-install: - The SDK needs to be installed without user interaction and without admin rights. dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs. dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.
> 
> dotnet-install: Calling: machine_has curl dotnet-install: Calling: calculate_vars dotnet-install: Calling: get_normalized_architecture_from_architecture dotnet-install: Calling: get_machine_architecture dotnet-install: Normalized architecture: 'arm64'. dotnet-install: Calling: get_normalized_os dotnet-install: Calling: get_current_os_name dotnet-install: Calling: get_linux_platform_name dotnet-install: Normalized OS: 'linux-musl'. dotnet-install: Calling: get_normalized_quality dotnet-install: Normalized quality: ''. dotnet-install: Calling: get_normalized_channel 6.0 dotnet-install: Normalized channel: '6.0'. dotnet-install: Calling: get_normalized_product dotnet-install: Normalized product: 'dotnet-sdk'. dotnet-install: Calling: resolve_installation_path dotnet-install: Calling: get_user_install_path dotnet-install: resolve_installation_path: user_install_path=/root/.dotnet dotnet-install: InstallRoot: '/root/.dotnet'. dotnet-install: Calling: get_normalized_architecture_for_specific_sdk_version Latest 6.0 arm64 dotnet-install: Calling: get_current_os_name dotnet-install: Calling: get_linux_platform_name dotnet-install: Calling: get_download_link_from_aka_ms dotnet-install: Retrieving primary payload URL from aka.ms for channel: '6.0', quality: '', product: 'dotnet-sdk', os: 'linux-musl', architecture: 'arm64'. dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz'. dotnet-install: Calling: get_http_header https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz true dotnet-install: Calling: machine_has curl dotnet-install: Calling: get_http_header_curl https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz true dotnet-install: Received response: HTTP/1.1 301 Moved Permanently Server: Kestrel Location: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz Request-Context: appId=cid-v1:7d63747b-487e-492a-872d-762362f77974 X-Response-Cache-Status: True Content-Length: 0 Expires: Sun, 27 Nov 2022 13:55:07 GMT Cache-Control: max-age=0, no-cache, no-store Pragma: no-cache Date: Sun, 27 Nov 2022 13:55:07 GMT Connection: keep-alive Strict-Transport-Security: max-age=31536000 ; includeSubDomains
> 
> HTTP/2 200 accept-ranges: bytes age: 364968 content-md5: SvTRpTqhouBq/1CwqRml+Q== content-type: application/octet-stream date: Sun, 27 Nov 2022 13:55:09 GMT etag: 0x8DAC0F9AC286E08 last-modified: Mon, 07 Nov 2022 19:52:59 GMT server: ECAcc (saa/8307) x-cache: HIT x-ms-blob-type: BlockBlob x-ms-lease-status: unlocked x-ms-request-id: 0f5a2aa1-801e-00f9-1416-fff289000000 x-ms-version: 2009-09-19 content-length: 179310623
> 
> dotnet-install: The redirect location retrieved: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz'. dotnet-install: Retrieved primary payload URL from aka.ms link: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz'. dotnet-install: Downloading using legacy url will not be attempted. dotnet-install: Version: '6.0.403'. dotnet-install: Calling: get_specific_product_version 6.0.403 https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz dotnet-install: Calling: get_specific_product_version_url 6.0.403 true https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/sdk-productVersion.txt dotnet-install: Calling: get_specific_product_version_url 6.0.403 false https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/dotnet-sdk-6.0.403-linux-musl-arm64.tar.gz dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/productVersion.txt dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.403/sdk-productVersion.txt dotnet-install: Calling: machine_has curl dotnet-install: Calling: is_dotnet_package_installed /root/.dotnet sdk 6.0.403 dotnet-install: Calling: combine_paths /root/.dotnet sdk dotnet-install: combine_paths: root_path=/root/.dotnet dotnet-install: combine_paths: child_path=sdk dotnet-install: Calling: combine_paths /root/.dotnet/sdk 6.0.403 dotnet-install: combine_paths: root_path=/root/.dotnet/sdk dotnet-install: combine_paths: child_path=6.0.403 dotnet-install: is_dotnet_package_installed: dotnet_package_path=/root/.dotnet/sdk/6.0.403 dotnet-install: .NET Core SDK with version '6.0.403' is already installed. 创建软链接... /dev/stdin: line 108: /usr/local/bin/dotnet: No such file or directory
> 
> -------set up dot net env finish-------

这个是bug，arm应该是没有/usr/local/bin目录，但与当前issue不一样，我转成一个新的issue了 #336
