### ISSUE TITLE
【Bug】青龙拉库后运行 bili扫码登录 报错

### ISSUE THREAD

**Issue by mxlt02** [RayWangQvQ/BiliBiliToolPro#538]
版本号：[最新版 ](https://github.com/RayWangQvQ/BiliBiliToolPro/commit/11f29155cff71093621ed8e6c9a5285172182706)
运行环境：Linux 青龙 2.15.14

问题描述：
拉库后运行
bili扫码登录
提示以下内容

日志信息：
## 开始执行... 2023-05-11 17:19:29

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.115

repo目录: /ql/data/repo
bili仓库目录: 

bili_task_login.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project.

**Comment by canxunwangluo** [comment]
我运行报错
# 开始执行... 2023-05-21 15:34:25

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.116

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error : Failed to download package 'Newtonsoft.Json.13.0.2' from 'https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.2/newtonsoft.json.13.0.2.nupkg'. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error : The download of 'https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.2/newtonsoft.json.13.0.2.nupkg' timed out because no data was received for 60000ms. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error :   Exception of type 'System.TimeoutException' was thrown. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error : The feed 'nuget.org [https://api.nuget.org/v3/index.json]' lists package 'Newtonsoft.Json.13.0.2' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error :   Unable to find package 'Newtonsoft.Json.13.0.2'. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]

The build failed. Fix the build errors and run again.


## 执行结束... 2023-05-21 15:48:03  耗时 818 秒

**Comment by MerryYe** [comment]
> 

你好 请问你解决这个问题了 么。我遇到这个问题了。
运行环境OpenWRT Docker 青龙面板 2.15.14
## 开始执行... 2023-05-29 21:12:33

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.116

repo目录: /ql/data/repo
bili仓库目录: 

bili_task_login.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project.

**Comment by 2366481012** [comment]
## 开始执行... 2023-07-06 11:16:52

which dotnet: /root/.dotnet/dotnet
开始安装dotnet
------尝试使用apk安装------
ERROR: unable to select packages:
  dotnet6-sdk (no such package):
    required by: world[dotnet6-sdk]
安装成功

repo目录: /ql/repo
bili仓库目录: /ql/repo/RayWangQvQ_BiliBiliToolPro_develop


## 执行结束... 2023-07-06 11:16:54 耗时 2 秒

**Comment by shinny-xionghongwei** [comment]
因为最新的青龙路径发生变化，将bili_task_base.sh 文件中的37行改为 bili_repo="RayWangQvQ*"就可以解决了

**Comment by MerryYe** [comment]
好的 感谢


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年7月29日 19:42
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [RayWangQvQ/BiliBiliToolPro] 【Bug】青龙拉库后运行 bili扫码登录 报错 (Issue #538)


因为最新的青龙路径发生变化，将bili_task_base.sh 文件中的37行改为 bili_repo="RayWangQvQ*"就可以解决了

―

**Comment by mxlt02** [comment]
> 因为最新的青龙路径发生变化，将bili_task_base.sh 文件中的37行改为 bili_repo="RayWangQvQ*"就可以解决了

谢谢

**Comment by l1049780665** [comment]
> 因为最新的青龙路径发生变化，将bili_task_base.sh 文件中的37行改为 bili_repo="RayWangQvQ*"就可以解决了

bili测试ck
## 开始执行... 2023-09-02 17:41:16

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.121

repo目录: /ql/data/repo
bili仓库目录: 

bili_task_test.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project.


## 执行结束... 2023-09-02 17:41:17  耗时 1 秒　　　　


bili_base
## 开始执行... 2023-09-02 17:41:16

bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.121

repo目录: /ql/data/repo
bili仓库目录: 



## 执行结束... 2023-09-02 17:41:17  耗时 1 秒　　　　　

改了之后还是运行报错,青龙v2.16.1

**Comment by gbc-star** [comment]
同问，改了路径也还是不行

**Comment by gbc-star** [comment]
而且似乎不是路径的问题，我看说路径问题的回复是七月底的，我看日志我的是前两天开始报错出问题的

**Comment by mxlt02** [comment]
可以试试我的配置,我一直用着没问题
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/57489136/eb208715-4170-4f41-951b-6fe60a9ccc99)
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/57489136/88fac40b-9b59-401c-bc42-d874f13060c6)

图中的文字信息方便复制
https://github.com/mxlt02/BiliBiliToolPro.git
0 1 * * * 
bili_task_.+\.sh
sh

注意如果你的服务器无法访问github请用代理
https://ghproxy.com/https://github.com/mxlt02/BiliBiliToolPro.git

**Comment by gbc-star** [comment]
已经解决了，是我傻了，没怎么动脑子。重新拉库就好了，我怎么一开始没想到。。。。。好蠢

**Comment by l1049780665** [comment]
> 可以试试我的配置,我一直用着没问题 [![image](https://user-images.githubusercontent.com/57489136/265202683-eb208715-4170-4f41-951b-6fe60a9ccc99.png)](javascript:void(0)) [![image](https://user-images.githubusercontent.com/57489136/265202690-88fac40b-9b59-401c-bc42-d874f13060c6.png)](javascript:void(0))
> 
> 图中的文字信息方便复制 https://github.com/mxlt02/BiliBiliToolPro.git 0 1 * * * bili_task_.+.sh sh
> 
> 第二步 将bili_task_base.sh 文件中的37行改为 bili_repo="mxlt02_BiliBiliToolPro_main"
> 
> 注意如果你的服务器无法访问github请用代理 https://ghproxy.com/https://github.com/mxlt02/BiliBiliToolPro.git

解决了，感谢，好用！
