### ISSUE TITLE
增加专栏投币选项

### ISSUE THREAD

**Issue by piaoxue1** [RayWangQvQ/BiliBiliToolPro#611]
专栏创建比视频创建更容易，同样可以投币获得经验，用大号对小号进行投币的话，这样小号能更快升级，同时能利用大号的硬币。

**Comment by Polaris-cn10086** [comment]
可以做到，但是需要一段时间来添加功能。（新建文件夹🤔）
主要最近时间不是很充裕。等我有时间来做一做

**Comment by Polaris-cn10086** [comment]
已经在写啦，具体进程请关注我fork出的仓库的develop分支
https://github.com/Polaris-cn10086/BiliBiliToolPro/tree/develop

**Comment by Polaris-cn10086** [comment]
@piaoxue1 功能已经提交PR #617  。

**Comment by nizhenyu2022** [comment]
牛啊，佬。但是能改成只投专栏or只投视频or 视频专栏随机投吗。

**Comment by nizhenyu2022** [comment]
> @piaoxue1 功能已经提交PR #617 。

能编译一份linux-musl-x64的吗，不胜感激

**Comment by Polaris-cn10086** [comment]
> 牛啊，佬。但是能改成只投专栏or只投视频or 视频专栏随机投吗。

emmm，目前视频投币和专栏投币是划分成两个功能的，要两个随机投的话我暂时还没能想到一个好的方法来实现。

等我有时间来试着搞一下吧。

**Comment by Polaris-cn10086** [comment]
> > @piaoxue1 功能已经提交PR #617 。
> 
> 能编译一份linux-musl-x64的吗，不胜感激

我研究一下

**Comment by nizhenyu2022** [comment]
> > > @piaoxue1 功能已经提交PR #617 。
> > 
> > 
> > 能编译一份linux-musl-x64的吗，不胜感激
> 
> 我研究一下

大佬，有编译好了吗，谢谢

**Comment by nizhenyu2022** [comment]
> > > @piaoxue1 功能已经提交PR #617 。
> > 
> > 
> > 能编译一份linux-musl-x64的吗，不胜感激
> 
> 我研究一下

大佬，我编译出来了，但是有问题啊。日志
2023-11-25 06:31:19.834 +08:00 [DBG] [REQUEST]
GET /x/space/wbi/article?w_rid=cf4053e88a81e29fe2a2febe1e07d1bc&wts=1700865071&mid=0&pn=1&ps=30&sort=publish_time HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://space.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

我已经配置了
    "SupportUpIds": "89620375,1934748162,1918964862",
为什么会mid=0呢？

**Comment by Polaris-cn10086** [comment]
> > > > @piaoxue1 功能已经提交PR #617 。
> > > 
> > > 
> > > 能编译一份linux-musl-x64的吗，不胜感激
> > 
> > 我研究一下
> 
> 大佬，我编译出来了，但是有问题啊。日志
> 2023-11-25 06:31:19.834 +08:00 [DBG] [REQUEST]
> GET /x/space/wbi/article?w_rid=cf4053e88a81e29fe2a2febe1e07d1bc&wts=1700865071&mid=0&pn=1&ps=30&sort=publish_time HTTP/1.1
> Referer: https://www.bilibili.com/
> Origin: https://space.bilibili.com
> Host: api.bilibili.com
> Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
> Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
> Sec-Fetch-Dest: empty
> Sec-Fetch-Mode: cors
> Sec-Fetch-Site: same-site
> Connection: keep-alive
> 
> 我已经配置了
>     "SupportUpIds": "89620375,1934748162,1918964862",
> 为什么会mid=0呢？

是根据今天凌晨的最新版编译的吗？

**Comment by nizhenyu2022** [comment]
> > > > > @piaoxue1 功能已经提交PR #617 。
> > > > 
> > > > 
> > > > 能编译一份linux-musl-x64的吗，不胜感激
> > > 
> > > 
> > > 我研究一下
> > 
> > 
> > 大佬，我编译出来了，但是有问题啊。日志
> > 2023-11-25 06:31:19.834 +08:00 [DBG] [REQUEST]
> > GET /x/space/wbi/article?w_rid=cf4053e88a81e29fe2a2febe1e07d1bc&wts=1700865071&mid=0&pn=1&ps=30&sort=publish_time HTTP/1.1
> > Referer: https://www.bilibili.com/
> > Origin: https://space.bilibili.com
> > Host: api.bilibili.com
> > Accept: application/json, text/plain, _/_, application/json; q=0.001, application/xml; q=0.001
> > Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
> > Sec-Fetch-Dest: empty
> > Sec-Fetch-Mode: cors
> > Sec-Fetch-Site: same-site
> > Connection: keep-alive
> > 我已经配置了
> > "SupportUpIds": "89620375,1934748162,1918964862",
> > 为什么会mid=0呢？
> 
> 是根据今天凌晨的最新版编译的吗？

对的是根据今天凌晨的最新版编译的，我改了一下，让它从mid.txt里面取mid,投币正常。还有可以增加，随机观看跟随机分享视频，可以也从自定义的UP里面优先取吗？

**Comment by Polaris-cn10086** [comment]
我用了一样的`SupportUpIds`没能复现出`mid=0`的问题
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/63545780/754aa984-485a-4033-9443-83ffae6c6b71)
GET /x/space/wbi/article?w_rid=04a3eed56f243160b2ac2df882dbcbdf&wts=1700878729&mid=1934748162&pn=1&ps=30&sort=publish_time HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://space.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

**Comment by Polaris-cn10086** [comment]
> > > > > > @piaoxue1 功能已经提交PR #617 。
> > > > > 
> > > > > 
> > > > > 能编译一份linux-musl-x64的吗，不胜感激
> > > > 
> > > > 
> > > > 我研究一下
> > > 
> > > 
> > > 大佬，我编译出来了，但是有问题啊。日志
> > > 2023-11-25 06:31:19.834 +08:00 [DBG] [REQUEST]
> > > GET /x/space/wbi/article?w_rid=cf4053e88a81e29fe2a2febe1e07d1bc&wts=1700865071&mid=0&pn=1&ps=30&sort=publish_time HTTP/1.1
> > > Referer: https://www.bilibili.com/
> > > Origin: https://space.bilibili.com
> > > Host: api.bilibili.com
> > > Accept: application/json, text/plain, _/_, application/json; q=0.001, application/xml; q=0.001
> > > Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
> > > Sec-Fetch-Dest: empty
> > > Sec-Fetch-Mode: cors
> > > Sec-Fetch-Site: same-site
> > > Connection: keep-alive
> > > 我已经配置了
> > > "SupportUpIds": "89620375,1934748162,1918964862",
> > > 为什么会mid=0呢？
> > 
> > 
> > 是根据今天凌晨的最新版编译的吗？
> 
> 对的是根据今天凌晨的最新版编译的，我改了一下，让它从mid.txt里面取mid,投币正常。还有可以增加，随机观看跟随机分享视频，可以也从自定义的UP里面优先取吗？

https://github.com/RayWangQvQ/BiliBiliToolPro/blob/9c8739f37a7dc738b5feb0df74526e06f23d21ac/src/Ray.BiliBiliTool.DomainService/VideoDomainService.cs#L276-L297

我看代码写的就是从自定义的UP里面优先取的

**Comment by piaoxue1** [comment]
docker环境下专栏投币失败。最新2.02winx64版也是投币失败。

![Snipaste_2023-12-09_12-10-56](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/58386584/98473a49-1deb-4c7e-af79-e1c4f6f1df0c)
这是winx64版运行的截图

**Comment by Polaris-cn10086** [comment]
> docker环境下专栏投币失败。最新2.02winx64版也是投币失败。
> 
> ![Snipaste_2023-12-09_12-10-56](https://private-user-images.githubusercontent.com/58386584/289232762-98473a49-1deb-4c7e-af79-e1c4f6f1df0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDMzOTksIm5iZiI6MTcwMjEwMzA5OSwicGF0aCI6Ii81ODM4NjU4NC8yODkyMzI3NjItOTg0NzNhNDktMWRlYi00YzdlLWFmNzktZTFjNGY2ZjFkZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA2MjQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYTg3NTYxNmQwOTMzMmE4ZTE0MTg5ZGVjY2ZhZTEyNTk2NGMyYjc2ZGIyOTU1NzdjNzRjNDQ1ZDRmN2Y0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KGt35j11_y-Hkj1lSDq6FCu6oqwidZ6MaAYog5JkXg0) 这是winx64版运行的截图

需要更详细的日志，请在日志文件中截取相关日志

**Comment by Polaris-cn10086** [comment]
> docker环境下专栏投币失败。最新2.02winx64版也是投币失败。
> 
> ![Snipaste_2023-12-09_12-10-56](https://private-user-images.githubusercontent.com/58386584/289232762-98473a49-1deb-4c7e-af79-e1c4f6f1df0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDMzOTksIm5iZiI6MTcwMjEwMzA5OSwicGF0aCI6Ii81ODM4NjU4NC8yODkyMzI3NjItOTg0NzNhNDktMWRlYi00YzdlLWFmNzktZTFjNGY2ZjFkZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA2MjQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYTg3NTYxNmQwOTMzMmE4ZTE0MTg5ZGVjY2ZhZTEyNTk2NGMyYjc2ZGIyOTU1NzdjNzRjNDQ1ZDRmN2Y0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KGt35j11_y-Hkj1lSDq6FCu6oqwidZ6MaAYog5JkXg0) 这是winx64版运行的截图

可能是`SupportUpIds`配置项的问题，我目前发现其会一直保持为空字符串，无论是否设置值。我找一找是怎么导致的。

**Comment by Polaris-cn10086** [comment]
@piaoxue1 出现该问题的情况可能有：
1. 没有配置`SupportUpIds`
2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。

**Comment by piaoxue1** [comment]
> @piaoxue1 出现该问题的情况可能有：
> 
> 1. 没有配置`SupportUpIds`
> 2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。

填写了开发环境配置后（即默认和开发supportUpIds都填写），专栏投币只投了2个，就转而投币视频了（目标账号1专栏有五个，bilitool只投了两个，supportupids顺序是账号1，账号2，账号3，cookie顺序是账号3，账号2，账号1）。将开发环境配置填入后（也就是生产、开发、默认配置的supportUpIds都正确填写后），又再次出现上述投币失败的情况。

**Comment by Polaris-cn10086** [comment]
> > @piaoxue1 出现该问题的情况可能有：
> > 
> > 1. 没有配置`SupportUpIds`
> > 2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。
> 
> 填写了开发环境配置后（即默认和开发supportUpIds都填写），专栏投币只投了2个，就转而投币视频了（目标账号1专栏有五个，bilitool只投了两个，supportupids顺序是账号1，账号2，账号3，cookie顺序是账号3，账号2，账号1）。将开发环境配置填入后（也就是生产、开发、默认配置的supportUpIds都正确填写后），又再次出现上述投币失败的情况。

需要详细的日志，在Logs文件夹中

**Comment by piaoxue1** [comment]
> > > @piaoxue1 出现该问题的情况可能有：
> > > 
> > > 1. 没有配置`SupportUpIds`
> > > 2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。
> > 
> > 
> > 填写了开发环境配置后（即默认和开发supportUpIds都填写），专栏投币只投了2个，就转而投币视频了（目标账号1专栏有五个，bilitool只投了两个，supportupids顺序是账号1，账号2，账号3，cookie顺序是账号3，账号2，账号1）。将开发环境配置填入后（也就是生产、开发、默认配置的supportUpIds都正确填写后），又再次出现上述投币失败的情况。
> 
> 需要详细的日志，在Logs文件夹中
> 
> 有一种可能是：supportUpIds的选取并不是顺序选取，而是随机的。每一次准备投币，都会在填写的所有账号中随机选取一个，如果被选到的正好是当前cookie的id的话，会使得函数返回值为0，导致出现请求错误

再次测试了一下，投币顺序是按照填写顺序随机选取的，然后如果想给单个账号多个专栏投币的话通过重复填写uid并不能实现预期效果，随机选取，而且会漏掉某些uid，逻辑实在是搞不清了。

**Comment by Polaris-cn10086** [comment]
> > > > @piaoxue1 出现该问题的情况可能有：
> > > > 
> > > > 1. 没有配置`SupportUpIds`
> > > > 2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。
> > > 
> > > 
> > > 填写了开发环境配置后（即默认和开发supportUpIds都填写），专栏投币只投了2个，就转而投币视频了（目标账号1专栏有五个，bilitool只投了两个，supportupids顺序是账号1，账号2，账号3，cookie顺序是账号3，账号2，账号1）。将开发环境配置填入后（也就是生产、开发、默认配置的supportUpIds都正确填写后），又再次出现上述投币失败的情况。
> > 
> > 
> > 需要详细的日志，在Logs文件夹中
> > 有一种可能是：supportUpIds的选取并不是顺序选取，而是随机的。每一次准备投币，都会在填写的所有账号中随机选取一个，如果被选到的正好是当前cookie的id的话，会使得函数返回值为0，导致出现请求错误
> 
> 再次测试了一下，投币顺序是按照填写顺序随机选取的，然后如果想给单个账号多个专栏投币的话通过重复填写uid并不能实现预期效果，随机选取，而且会漏掉某些uid，逻辑实在是搞不清了。

对于专栏投币判断的逻辑好像是有些问题，等我找时间理一下。

如果随机到的专栏是投过币的话，会直接return，而不是进行下一次循环。就导致了投币数额低于预期

**Comment by nizhenyu2022** [comment]
> > > > > @piaoxue1 出现该问题的情况可能有：
> > > > > 
> > > > > 1. 没有配置`SupportUpIds`
> > > > > 2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。
> > > > 
> > > > 
> > > > 填写了开发环境配置后（即默认和开发supportUpIds都填写），专栏投币只投了2个，就转而投币视频了（目标账号1专栏有五个，bilitool只投了两个，supportupids顺序是账号1，账号2，账号3，cookie顺序是账号3，账号2，账号1）。将开发环境配置填入后（也就是生产、开发、默认配置的supportUpIds都正确填写后），又再次出现上述投币失败的情况。
> > > 
> > > 
> > > 需要详细的日志，在Logs文件夹中
> > > 有一种可能是：supportUpIds的选取并不是顺序选取，而是随机的。每一次准备投币，都会在填写的所有账号中随机选取一个，如果被选到的正好是当前cookie的id的话，会使得函数返回值为0，导致出现请求错误
> > 
> > 
> > 再次测试了一下，投币顺序是按照填写顺序随机选取的，然后如果想给单个账号多个专栏投币的话通过重复填写uid并不能实现预期效果，随机选取，而且会漏掉某些uid，逻辑实在是搞不清了。
> 
> 对于专栏投币判断的逻辑好像是有些问题，等我找时间理一下。
> 
> 如果随机到的专栏是投过币的话，会直接return，而不是进行下一次循环。就导致了投币数额低于预期

大佬，哔站是不是改动接口了，这两天投币都提示权限不足。

**Comment by Polaris-cn10086** [comment]
> > > > > > @piaoxue1 出现该问题的情况可能有：
> > > > > > 
> > > > > > 1. 没有配置`SupportUpIds`
> > > > > > 2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。
> > > > > 
> > > > > 
> > > > > 填写了开发环境配置后（即默认和开发supportUpIds都填写），专栏投币只投了2个，就转而投币视频了（目标账号1专栏有五个，bilitool只投了两个，supportupids顺序是账号1，账号2，账号3，cookie顺序是账号3，账号2，账号1）。将开发环境配置填入后（也就是生产、开发、默认配置的supportUpIds都正确填写后），又再次出现上述投币失败的情况。
> > > > 
> > > > 
> > > > 需要详细的日志，在Logs文件夹中
> > > > 有一种可能是：supportUpIds的选取并不是顺序选取，而是随机的。每一次准备投币，都会在填写的所有账号中随机选取一个，如果被选到的正好是当前cookie的id的话，会使得函数返回值为0，导致出现请求错误
> > > 
> > > 
> > > 再次测试了一下，投币顺序是按照填写顺序随机选取的，然后如果想给单个账号多个专栏投币的话通过重复填写uid并不能实现预期效果，随机选取，而且会漏掉某些uid，逻辑实在是搞不清了。
> > 
> > 对于专栏投币判断的逻辑好像是有些问题，等我找时间理一下。
> > 
> > 如果随机到的专栏是投过币的话，会直接return，而不是进行下一次循环。就导致了投币数额低于预期
> 
> 大佬，哔站是不是改动接口了，这两天投币都提示权限不足。

如果可以试试pr中的版本，需要自己编译一下，还是不行的话等我明天看看。

**Comment by nizhenyu2022** [comment]
> > > > > > > @piaoxue1 出现该问题的情况可能有：
> > > > > > > 
> > > > > > > 1. 没有配置`SupportUpIds`
> > > > > > > 2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。
> > > > > > 
> > > > > > 
> > > > > > 填写了开发环境配置后（即默认和开发supportUpIds都填写），专栏投币只投了2个，就转而投币视频了（目标账号1专栏有五个，bilitool只投了两个，supportupids顺序是账号1，账号2，账号3，cookie顺序是账号3，账号2，账号1）。将开发环境配置填入后（也就是生产、开发、默认配置的supportUpIds都正确填写后），又再次出现上述投币失败的情况。
> > > > > 
> > > > > 
> > > > > 需要详细的日志，在Logs文件夹中
> > > > > 有一种可能是：supportUpIds的选取并不是顺序选取，而是随机的。每一次准备投币，都会在填写的所有账号中随机选取一个，如果被选到的正好是当前cookie的id的话，会使得函数返回值为0，导致出现请求错误
> > > > 
> > > > 
> > > > 再次测试了一下，投币顺序是按照填写顺序随机选取的，然后如果想给单个账号多个专栏投币的话通过重复填写uid并不能实现预期效果，随机选取，而且会漏掉某些uid，逻辑实在是搞不清了。
> > > 
> > > 
> > > 对于专栏投币判断的逻辑好像是有些问题，等我找时间理一下。
> > > 如果随机到的专栏是投过币的话，会直接return，而不是进行下一次循环。就导致了投币数额低于预期
> > 
> > 
> > 大佬，哔站是不是改动接口了，这两天投币都提示权限不足。
> 
> 如果可以试试pr中的版本，需要自己编译一下，还是不行的话等我明天看看。

需要贴日志给您看吗

**Comment by Polaris-cn10086** [comment]
> > > > > > > > @piaoxue1 出现该问题的情况可能有：
> > > > > > > > 
> > > > > > > > 1. 没有配置`SupportUpIds`
> > > > > > > > 2. 用`appsettings.json`设置了`SupportUpIds`，该配置可能会被`appsettings.Production.json`中的空配置覆盖。
> > > > > > > 
> > > > > > > 
> > > > > > > 填写了开发环境配置后（即默认和开发supportUpIds都填写），专栏投币只投了2个，就转而投币视频了（目标账号1专栏有五个，bilitool只投了两个，supportupids顺序是账号1，账号2，账号3，cookie顺序是账号3，账号2，账号1）。将开发环境配置填入后（也就是生产、开发、默认配置的supportUpIds都正确填写后），又再次出现上述投币失败的情况。
> > > > > > 
> > > > > > 
> > > > > > 需要详细的日志，在Logs文件夹中
> > > > > > 有一种可能是：supportUpIds的选取并不是顺序选取，而是随机的。每一次准备投币，都会在填写的所有账号中随机选取一个，如果被选到的正好是当前cookie的id的话，会使得函数返回值为0，导致出现请求错误
> > > > > 
> > > > > 
> > > > > 再次测试了一下，投币顺序是按照填写顺序随机选取的，然后如果想给单个账号多个专栏投币的话通过重复填写uid并不能实现预期效果，随机选取，而且会漏掉某些uid，逻辑实在是搞不清了。
> > > > 
> > > > 
> > > > 对于专栏投币判断的逻辑好像是有些问题，等我找时间理一下。
> > > > 如果随机到的专栏是投过币的话，会直接return，而不是进行下一次循环。就导致了投币数额低于预期
> > > 
> > > 
> > > 大佬，哔站是不是改动接口了，这两天投币都提示权限不足。
> > 
> > 如果可以试试pr中的版本，需要自己编译一下，还是不行的话等我明天看看。
> 
> 需要贴日志给您看吗  

可以，贴一下我看一下吧，但是得明天再琢磨着改

**Comment by nizhenyu2022** [comment]
2023-12-21 00:12:37.047 +08:00 [INF] 【投币前余额】 : 107
2023-12-21 00:12:37.048 +08:00 [DBG] 开始尝试第0次
2023-12-21 00:12:37.050 +08:00 [DBG] 随机挑选的 up 主为 305274402
2023-12-21 00:12:39.167 +08:00 [DBG] [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Wed, 20 Dec 2023 16:12:39 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Origin: https://www.bilibili.com
Bili-Status-Code: 0
Bili-Trace-Id: 18d81d126c658312
Vary: Origin
X-Bili-Trace-Id: 0233085128c81d9a18d81d126c658312
X-Ticket-Status: 1
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
Cross-Origin-Resource-Policy: cross-origin
Access-Control-Expose-Headers: X-Bili-Gaia-Vvoucher,X-Bili-Trace-Id, X-Cache-Webcdn
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone04
Content-Type: application/json; charset=utf-8
Expires: Wed, 20 Dec 2023 16:12:38 GMT
Content-Length: 2377

{"code":0,"message":"0","ttl":1,"data":{"isLogin":true,"email_verified":0,"face":"https://i2.hdslb.com/bfs/face/5dd47b69cdabfd5fedb279af187bdc1d94dfdee2.jpg","face_nft":0,"face_nft_type":0,"level_info":{"current_level":5,"current_min":10800,"current_exp":25668,"next_exp":28800},"mid":389770790,"mobile_verified":1,"money":107,"moral":70,"official":{"role":0,"title":"","desc":"","type":-1},"officialVerify":{"type":-1,"desc":""},"pendant":{"pid":2360,"name":"#EveOneCat","image":"https://i2.hdslb.com/bfs/garb/item/3a6053f073f979a776e02e088dd7dd7694c5b1f3.png","expire":0,"image_enhance":"https://i2.hdslb.com/bfs/garb/item/6c7f2ccb92627b11101dfbb616524845cac8f216.webp","image_enhance_frame":"https://i2.hdslb.com/bfs/garb/item/99eba858b77f9c0f95ebbd1595968971daccfe7e.png","n_pid":2360},"scores":0,"uname":"小巷与浪人Toroxw","vipDueDate":1689436800000,"vipStatus":0,"vipType":1,"vip_pay_type":0,"vip_theme_type":0,"vip_label":{"path":"","text":"","label_theme":"","text_color":"","bg_style":0,"bg_color":"","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/d7b702ef65a976b20ed854cbd04cb9e27341bb79.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/KJunwh19T5.png"},"vip_avatar_subscript":0,"vip_nickname_color":"","vip":{"type":1,"status":0,"due_date":1689436800000,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"","label_theme":"","text_color":"","bg_style":0,"bg_color":"","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/d7b702ef65a976b20ed854cbd04cb9e27341bb79.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/KJunwh19T5.png"},"avatar_subscript":0,"nickname_color":"","role":0,"avatar_subscript_url":"","tv_vip_status":0,"tv_vip_pay_type":0,"tv_due_date":0},"wallet":{"mid":389770790,"bcoin_balance":0,"coupon_balance":0,"coupon_due_time":0},"has_shop":false,"shop_url":"","allowance_count":0,"answer_status":0,"is_senior_member":0,"wbi_img":{"img_url":"https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png","sub_url":"https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png"},"is_jury":false}

[ELAPSED] 00:00:02.1085057
2023-12-21 00:12:39.167 +08:00 [DBG] 【img_url】https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png
2023-12-21 00:12:39.167 +08:00 [DBG] 【sub_url】https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png
2023-12-21 00:12:41.279 +08:00 [DBG] [REQUEST]
GET /x/space/wbi/article?w_rid=5976b4e6331d08594fe26dac5bb58891&wts=1703088759&mid=305274402&pn=1&ps=30&sort=publish_time HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://space.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Wed, 20 Dec 2023 16:12:41 GMT
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Origin: https://space.bilibili.com
Access-Control-Expose-Headers: X-Bili-Gaia-Vvoucher,X-Bili-Trace-Id
Bili-Status-Code: -403
Bili-Trace-Id: 242ba9587e658312
Vary: Origin
X-Bili-Trace-Id: 29846ab2559d6d52242ba9587e658312
X-Client-Sign: 5976b4e6331d08594fe26dac5bb58891
X-Rid-Result: 1
X-Ticket-Status: 1
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
Cross-Origin-Resource-Policy: cross-origin
IDC: shjd
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone04
Content-Type: application/json; charset=utf-8
Content-Length: 52
Expires: Wed, 20 Dec 2023 16:12:40 GMT

{"code":-403,"message":"访问权限不足","ttl":1}

[ELAPSED] 00:00:02.1073323
2023-12-21 00:12:41.307 +08:00 [ERR] 投币失败，继续其他任务。失败信息:访问权限不足

2023-12-21 00:12:41.309 +08:00 [INF] -----结束-----


提示这样，https://github.com/SocialSisterYi/bilibili-API-collect/issues/912
跟这个报错一样都是权限不足

**Comment by Polaris-cn10086** [comment]
@nizhenyu2022 问题我复现了，你要不单独开个issue，方便我到时候修bug。

**Comment by nizhenyu2022** [comment]
> Reference in new i
已经开了新的issues，https://github.com/RayWangQvQ/BiliBiliToolPro/issues/643
麻烦大佬看看，新版专栏投币还是有问题，而视频则可以。

**Comment by RayWangQvQ** [comment]
专栏投币Feature当前已包含，具体其他bug可以单独开issue，这个先关闭了。
感谢contributor贡献PR！
